# TCL File Generated by Component Editor 13.0sp1
# Mon Jun 29 18:19:20 IRDT 2015
# DO NOT MODIFY


# 
# iic_controller "iic_controller" v1.0
#  2015.06.29.18:19:20
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module iic_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME iic_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME iic_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL i2c_master_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file i2c_master_bit_ctrl.v VERILOG PATH iic_controller/i2c_master_bit_ctrl.v
add_fileset_file i2c_master_byte_ctrl.v VERILOG PATH iic_controller/i2c_master_byte_ctrl.v
add_fileset_file i2c_master_defines.v VERILOG PATH iic_controller/i2c_master_defines.v
add_fileset_file i2c_master_top.v VERILOG PATH iic_controller/i2c_master_top.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL i2c_master_top
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file i2c_master_bit_ctrl.v VERILOG PATH iic_controller/i2c_master_bit_ctrl.v
add_fileset_file i2c_master_byte_ctrl.v VERILOG PATH iic_controller/i2c_master_byte_ctrl.v
add_fileset_file i2c_master_defines.v VERILOG PATH iic_controller/i2c_master_defines.v
add_fileset_file i2c_master_top.v VERILOG PATH iic_controller/i2c_master_top.v


# 
# parameters
# 
add_parameter ARST_LVL STD_LOGIC_VECTOR 0 ""
set_parameter_property ARST_LVL DEFAULT_VALUE 0
set_parameter_property ARST_LVL DISPLAY_NAME ARST_LVL
set_parameter_property ARST_LVL WIDTH 32
set_parameter_property ARST_LVL TYPE STD_LOGIC_VECTOR
set_parameter_property ARST_LVL UNITS None
set_parameter_property ARST_LVL DESCRIPTION ""
set_parameter_property ARST_LVL HDL_PARAMETER true


# 
# display items
# 


# 
# connection point iic_master_mem
# 
add_interface iic_master_mem avalon end
set_interface_property iic_master_mem addressUnits WORDS
set_interface_property iic_master_mem associatedClock clock
set_interface_property iic_master_mem associatedReset reset
set_interface_property iic_master_mem bitsPerSymbol 8
set_interface_property iic_master_mem burstOnBurstBoundariesOnly false
set_interface_property iic_master_mem burstcountUnits WORDS
set_interface_property iic_master_mem explicitAddressSpan 0
set_interface_property iic_master_mem holdTime 0
set_interface_property iic_master_mem linewrapBursts false
set_interface_property iic_master_mem maximumPendingReadTransactions 0
set_interface_property iic_master_mem readLatency 0
set_interface_property iic_master_mem readWaitTime 1
set_interface_property iic_master_mem setupTime 0
set_interface_property iic_master_mem timingUnits Cycles
set_interface_property iic_master_mem writeWaitTime 0
set_interface_property iic_master_mem ENABLED true
set_interface_property iic_master_mem EXPORT_OF ""
set_interface_property iic_master_mem PORT_NAME_MAP ""
set_interface_property iic_master_mem SVD_ADDRESS_GROUP ""

add_interface_port iic_master_mem wb_dat_o readdata Output 8
add_interface_port iic_master_mem wb_ack_o waitrequest_n Output 1
add_interface_port iic_master_mem wb_adr_i address Input 3
add_interface_port iic_master_mem wb_we_i write Input 1
add_interface_port iic_master_mem wb_dat_i writedata Input 8
add_interface_port iic_master_mem wb_cyc_i chipselect Input 1
set_interface_assignment iic_master_mem embeddedsw.configuration.isFlash 0
set_interface_assignment iic_master_mem embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment iic_master_mem embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment iic_master_mem embeddedsw.configuration.isPrintableDevice 0


# 
# connection point iic_master_irq
# 
add_interface iic_master_irq interrupt end
set_interface_property iic_master_irq associatedAddressablePoint iic_master_mem
set_interface_property iic_master_irq associatedReset reset
set_interface_property iic_master_irq ENABLED true
set_interface_property iic_master_irq EXPORT_OF ""
set_interface_property iic_master_irq PORT_NAME_MAP ""
set_interface_property iic_master_irq SVD_ADDRESS_GROUP ""

add_interface_port iic_master_irq wb_inta_o irq Output 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock wb_clk_i clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset arst_i reset_n Input 1


# 
# connection point inout
# 
add_interface inout conduit end
set_interface_property inout associatedClock clock
set_interface_property inout associatedReset reset
set_interface_property inout ENABLED true
set_interface_property inout EXPORT_OF ""
set_interface_property inout PORT_NAME_MAP ""
set_interface_property inout SVD_ADDRESS_GROUP ""

add_interface_port inout scl_pad_i scl_in Input 1
add_interface_port inout scl_padoen_o scl_outen Output 1
add_interface_port inout sda_pad_i sda_in Input 1
add_interface_port inout sda_pad_o sda_out Output 1
add_interface_port inout sda_padoen_o sda_outen Output 1
add_interface_port inout wb_rst_i always0 Input 1
add_interface_port inout scl_pad_o scl_out Output 1
add_interface_port inout wb_stb_i always1 Input 1

